# Generated by Django 4.2.6 on 2023-12-27 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_remove_follow_follower_user_follower_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follower",
        ),
        migrations.AddField(
            model_name="follow",
            name="follower",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
