# Generated by Django 4.2.6 on 2023-12-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0006_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name=""
            ),
        ),
    ]
