# Generated by Django 4.2.6 on 2024-01-02 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0008_alter_follow_follower_alter_follow_following_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="following",
            new_name="followee",
        ),
    ]
