# Generated by Django 4.2.6 on 2025-03-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_time',
            new_name='timestamp',
        ),
    ]
